### PR TITLE
Fixed adding deleted products

### LINKED ISSUE #210: Fix adding deleted products
Once a product is removed from recipe you cant add it again

### PR DESCRIPTION
**Pull request by Honsiu**
Fixes #210

### CODE REVIEW

File: admin/src/routes/(authenticated)/recipes/Parts.svelte [hunk 1]
```diff
@@ -50,35 +50,38 @@
...
-      newParts = [];
-    }
     if (deleteParts) {
       deleteParts.forEach(
-        ({ id }) =>
-          id &&
-          genericUpdate(supabase.from("recipe_part").delete().match({ id }), {
+        ({ product_id }) =>
+          product_id &&
+          genericUpdate(supabase.from("recipe_part").delete().match({ product_id }), {
```
Comment (michalstruck) [inline admin/src/routes/(authenticated)/recipes/Parts.svelte]: I think this would delete all `recipe_part` records that have a matching `product_id` - so would result in data loss across unrelated recipes. Let's not do that 😇😅
We should match by `recipe_part.id`

File: admin/src/routes/(authenticated)/recipes/Parts.svelte [hunk 2]
```diff
@@ -50,35 +50,38 @@
     unsavedChanges = true;
   };
 
-  const deletePart = (partIndex: number) => {
+  $: console.log({ parts, newParts, deleteParts });
```
Comment (michalstruck) [inline admin/src/routes/(authenticated)/recipes/Parts.svelte]: Let's get rid of console logs

File: admin/src/routes/(authenticated)/recipes/Parts.svelte [hunk 3]
```diff
@@ -50,35 +50,38 @@
...
+
+  const deletePart = (partToDelete: Part) => {
     unsavedChanges = true;
-    deleteParts = [...deleteParts, parts[partIndex]];
-    parts = parts.filter((_, i) => i !== partIndex);
+    deleteParts = [...deleteParts, partToDelete];
+    newParts = newParts.filter((newPart) => newPart.product_id !== partToDelete.product_id);
+    parts = parts.filter((part) => part.product_id !== partToDelete.product_id && part.id == null);
```
Comment (michalstruck) [inline admin/src/routes/(authenticated)/recipes/Parts.svelte]: I know that I requested the `&& part.id == null` check in person, but maybe let's revisit if it's really needed.
This would only filter out if the part came from the backend right? (`part.id` is only present in backend data)

**Review by michalstruck — CHANGES_REQUESTED** [review]

File: admin/src/routes/(authenticated)/recipes/Parts.svelte (hunk 1 above)
Comment (Honsiu) [reply admin/src/routes/(authenticated)/recipes/Parts.svelte]: Right, I'll switch it back

File: admin/src/routes/(authenticated)/recipes/Parts.svelte (hunk 3 above)
Comment (Honsiu) [reply admin/src/routes/(authenticated)/recipes/Parts.svelte]: Yeah, now when i checked it results in removing all parts that were newly added (cause untill they're written into db they don't have id) 😵‍💫

**Review by michalstruck — APPROVED** [review]
