### PR TITLE
fixed adding part before save

### LINKED ISSUE #205: Fix unadded product on saving a recipe
When you fill input for a new ingredient and save recipe, it wont be added

### PR DESCRIPTION
**Pull request by Honsiu**
Fixes #205

### CODE REVIEW

File: admin/src/routes/(authenticated)/recipes/Parts.svelte [hunk 1]
```diff
@@ -29,11 +29,17 @@
 
   let partErrorModal = false;
 
-  const productItems = products.map((p) => ({ name: p.name, value: p.id }));
+  $: productItems = products
+    .map((p) => ({ name: p.name, value: p.id }))
+    .filter(
+      (p) =>
+        !newParts.find((newPart) => newPart.product_id == p.value) ||
+        deleteParts.find((deletedPart) => deletedPart.product_id == p.value)
```
Comment (michalstruck) [inline admin/src/routes/(authenticated)/recipes/Parts.svelte]: Please use strict equality checks here

Comment (Honsiu) [reply admin/src/routes/(authenticated)/recipes/Parts.svelte]: Alright. My bad

**Review by michalstruck — APPROVED** [review]
